Nix some MacOS stuff

diff --git a/src/slimerjs b/src/slimerjs
--- a/src/slimerjs
+++ b/src/slimerjs
@@ -27,13 +27,8 @@ then
     if [ "$SLIMERJSLAUNCHER" == "" ]
     then
         # Try the Mac OSX global default application path
-        if [ -f "/Applications/Firefox.app/Contents/MacOS/firefox" ]
-        then
-            SLIMERJSLAUNCHER="/Applications/Firefox.app/Contents/MacOS/firefox"
-        else
-            echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox"
-            exit 1
-        fi
+        echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox"
+        exit 1
     fi
 fi
 
